# Melbourne house with VIC stamp duty
buy:
  purchase_price: 750000
  deposit_pct: 0.20
  mortgage_rate: 0.062
  mortgage_term_years: 30
  property_appreciation_rate: 0.045
  state: VIC
  first_home_buyer: false

rent:
  weekly_rent: 580
  rent_increase_rate: 0.04

investment:
  return_rate: 0.07
  dividend_yield: 0.02

tax:
  gross_income: 160000

inflation_rate: 0.03
time_horizon_years: 30
existing_savings: 200000
